ssh: handle non-existant _keepalive object
If the keepalive was never started, self._keepalive is None, signal this
correctly instead of generating the following backtrace:

  self = SSHDriver(target=Target(name='Test', env=None), name='ssh', state=<BindingState.bound: 1>, keyfile='', stderr_merge=False)

  def _check_keepalive(self):
>       return self._keepalive.poll() is None
E       AttributeError: 'NoneType' object has no attribute 'poll'

Implement this for both the SSH utility class used for proxying and the
SSHDriver.

Signed-off-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>